/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.2 at Tue Feb 19 20:55:37 2019. */

#include "messages.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t Report_fields[4] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, Report, nodeId, nodeId, 0),
    PB_FIELD(  2, INT32   , OPTIONAL, STATIC  , OTHER, Report, sensorType, nodeId, 0),
    PB_FIELD(  3, FLOAT   , OPTIONAL, STATIC  , OTHER, Report, value, sensorType, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
