/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.2 at Mon Feb 18 20:16:25 2019. */

#ifndef PB_TOBALR_MESSAGES_PB_H_INCLUDED
#define PB_TOBALR_MESSAGES_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _tobalr_Report {
    pb_callback_t deviceName;
    pb_callback_t reading;
/* @@protoc_insertion_point(struct:tobalr_Report) */
} tobalr_Report;

typedef struct _tobalr_Reading {
    pb_callback_t name;
    float value;
/* @@protoc_insertion_point(struct:tobalr_Reading) */
} tobalr_Reading;

/* Default values for struct fields */

/* Initializer values for message structs */
#define tobalr_Report_init_default               {{{NULL}, NULL}, {{NULL}, NULL}}
#define tobalr_Reading_init_default              {{{NULL}, NULL}, 0}
#define tobalr_Report_init_zero                  {{{NULL}, NULL}, {{NULL}, NULL}}
#define tobalr_Reading_init_zero                 {{{NULL}, NULL}, 0}

/* Field tags (for use in manual encoding/decoding) */
#define tobalr_Report_deviceName_tag             1
#define tobalr_Report_reading_tag                2
#define tobalr_Reading_name_tag                  3
#define tobalr_Reading_value_tag                 4

/* Struct field encoding specification for nanopb */
extern const pb_field_t tobalr_Report_fields[3];
extern const pb_field_t tobalr_Reading_fields[3];

/* Maximum encoded size of messages (where known) */
/* tobalr_Report_size depends on runtime parameters */
/* tobalr_Reading_size depends on runtime parameters */

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define MESSAGES_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
