/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.2 at Mon Feb 18 20:16:25 2019. */

#include "messages.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t tobalr_Report_fields[3] = {
    PB_FIELD(  1, STRING  , REQUIRED, CALLBACK, FIRST, tobalr_Report, deviceName, deviceName, 0),
    PB_FIELD(  2, MESSAGE , REPEATED, CALLBACK, OTHER, tobalr_Report, reading, deviceName, &tobalr_Reading_fields),
    PB_LAST_FIELD
};

const pb_field_t tobalr_Reading_fields[3] = {
    PB_FIELD(  3, STRING  , REQUIRED, CALLBACK, FIRST, tobalr_Reading, name, name, 0),
    PB_FIELD(  4, FLOAT   , REQUIRED, STATIC  , OTHER, tobalr_Reading, value, name, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
